-- Create table "brand" if it doesn't exist
CREATE TABLE IF NOT EXISTS brand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
    );

-- Create table "category" if it doesn't exist
CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
    );

-- Create table "item" if it doesn't exist
CREATE TABLE IF NOT EXISTS item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    price DOUBLE NOT NULL,
    stock_quantity INT CHECK (stock_quantity >= 0),
    imageURL VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    brand_id BIGINT NOT NULL,
    FOREIGN KEY (brand_id) REFERENCES brand(id)
    );


-- Create table "item_category" if it doesn't exist
CREATE TABLE IF NOT EXISTS item_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (category_id) REFERENCES category(id)
    );

-- Remove previous data in the brand table to avoid duplicates
DELETE FROM brand WHERE name IN ('Apple', 'Samsung', 'Sony', 'Nike', 'Adidas', 'Puma');

-- Insert data into the "brand" table
INSERT INTO brand (name, description)
VALUES
    ('Apple', 'Leading technology company known for iPhones, MacBooks, and more'),
    ('Samsung', 'Global electronics manufacturer offering a wide range of smartphones, TVs, and appliances'),
    ('Sony', 'Japanese multinational specializing in electronics, gaming, and entertainment'),
    ('Nike', 'Worldwide leader in sportswear and footwear'),
    ('Adidas', 'German company known for its sports apparel, shoes, and accessories'),
    ('Puma', 'Global brand known for athletic footwear and lifestyle products');

-- Remove previous data in the category table to avoid duplicates
DELETE FROM category WHERE name IN ('Electronics', 'Fashion', 'Home Appliances', 'Footwear', 'Sports Equipment', 'Accessories');

-- Insert data into the "category" table
INSERT INTO category (name, description)
VALUES
    ('Electronics', 'Devices such as smartphones, laptops, and TVs'),
    ('Fashion', 'Clothing, accessories, and trendy items'),
    ('Home Appliances', 'Household items such as refrigerators, washing machines, and kitchen gadgets'),
    ('Footwear', 'Shoes, boots, and sandals for men, women, and children'),
    ('Sports Equipment', 'Gear for different sports including balls, rackets, and protective equipment'),
    ('Accessories', 'Items like watches, sunglasses, and jewelry');

-- Remove previous data in the item table to avoid duplicates
DELETE FROM item WHERE name IN ('iPhone 13', 'Galaxy S21', 'PlayStation 5', 'Nike Air Max', 'Adidas Ultraboost', 'Puma Suede Classic');

-- Insert data into the "item" table
INSERT INTO item (name, description, price, stock_quantity, imageURL, created_at, updated_at, brand_id)
VALUES
    ('iPhone 13', 'Apple smartphone with 5G technology and A15 Bionic chip', 999.99, 150, 'https://example.com/iphone13.jpg', NOW(), NOW(), 1),
    ('Galaxy S21', 'Samsung flagship smartphone with 120Hz display and powerful performance', 799.99, 100, 'https://example.com/galaxys21.jpg', NOW(), NOW(), 2),
    ('PlayStation 5', 'Sony gaming console with 4K support and ultra-fast SSD', 499.99, 50, 'https://example.com/ps5.jpg', NOW(), NOW(), 3),
    ('Nike Air Max', 'Iconic Nike running shoes with air cushioning', 129.99, 200, 'https://example.com/nikeairmax.jpg', NOW(), NOW(), 4),
    ('Adidas Ultraboost', 'Adidas high-performance running shoes with boost technology', 180.00, 120, 'https://example.com/adidasultraboost.jpg', NOW(), NOW(), 5),
    ('Puma Suede Classic', 'Classic Puma shoes with a timeless design', 89.99, 80, 'https://example.com/pumasuedeclassic.jpg', NOW(), NOW(), 6);


-- Remove previous data in the item_category table to avoid duplicates
DELETE FROM item_category WHERE item_id IN (1, 2, 3, 4, 5, 6);

-- Insert data into the "item_category" table
INSERT INTO item_category (item_id, category_id)
VALUES
    (1, 1), -- iPhone 13 belongs to Electronics
    (2, 1), -- Galaxy S21 belongs to Electronics
    (3, 1), -- PlayStation 5 belongs to Electronics
    (4, 4), -- Nike Air Max belongs to Footwear
    (5, 4), -- Adidas Ultraboost belongs to Footwear
    (6, 4); -- Puma Suede Classic belongs to Footwear
